version: 2
updates:
  # Dependencies listed in .github/workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Dependencies"
      - "github_actions"
      - "kind/changelog-not-required"
  # Dependencies listed in go.mod
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    labels:
      - "kind/changelog-not-required"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
  # Docker base images in Dockerfiles
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Dependencies"
      - "docker"
      - "kind/changelog-not-required"
