name: velero
title: "Velero: Backup and migrate Kubernetes applications and their persistent volumes"
baseurl: /velero
google_analytics: FILL_OUT
latest: v0.11.0
versions:
- v1.0.0-beta.1
- v0.11.0
- v0.10.0
- v0.9.0
- v0.8.1
- v0.8.0
- v0.7.1
- v0.7.0
- v0.6.0
- v0.5.0
- v0.4.0
- v0.3.0
versioning: true
logo: assets/img/logo.svg
exclude:
- gen_version.sh
plugins:
- jekyll-redirect-from
contact:
  google: https://groups.google.com/forum/#!forum/projectvelero
  github: https://github.com/heptio/velero
  twitter: https://twitter.com/projectvelero
  slack: https://kubernetes.slack.com/messages/velero
defaults:
- scope:
    path: master
  values:
    version: master
    gh: https://github.com/heptio/velero/tree/master
- scope:
    path: v1.0.0-beta.1
  values:
    version: v1.0.0-beta.1
    gh: https:/github.com/heptio/velero/tree/v1.0.0-beta.1
- scope:
    path: v0.11.0
  values:
    version: v0.11.0
    gh: https:/github.com/heptio/velero/tree/v0.11.0
- scope:
    path: v0.10.0
  values:
    version: v0.10.0
    gh: https:/github.com/heptio/velero/tree/v0.10.0
- scope:
    path: v0.9.0
  values:
    version: v0.9.0
    gh: https:/github.com/heptio/velero/tree/v0.9.0
- scope:
    path: v0.8.1
  values:
    version: v0.8.1
    gh: https:/github.com/heptio/velero/tree/v0.8.1
- scope:
    path: v0.8.0
  values:
    version: v0.8.0
    gh: https:/github.com/heptio/velero/tree/v0.8.0
- scope:
    path: v0.7.1
  values:
    version: v0.7.1
    gh: https://github.com/heptio/velero/tree/v0.7.1
- scope:
    path: v0.7.0
  values:
    version: v0.7.0
    gh: https://github.com/heptio/velero/tree/v0.7.0
- scope:
    path: v0.6.0
  values:
    version: v0.6.0
    gh: https://github.com/heptio/velero/tree/v0.6.0
- scope:
    path: v0.5.0
  values:
    version: v0.5.0
    gh: https://github.com/heptio/velero/tree/v0.5.0
- scope:
    path: v0.4.0
  values:
    version: v0.4.0
    gh: https://github.com/heptio/velero/tree/v0.4.0
- scope:
    path: v0.3.0
  values:
    version: v0.3.0
    gh: https://github.com/heptio/velero/tree/v0.3.0
