
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = [
  "k8s.io/code-generator/cmd/client-gen",
  # needed by generated clientsets, but not an explicit dep in client-gen itself
  "k8s.io/apimachinery/pkg/apimachinery/registered",

  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
]

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.11.0"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "~10.2.1-beta"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "~8.1.x"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.10.26"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/robfig/cron"
  revision = "df38d32658d8788cd446ba74db4bb5375c4b0cb3"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/satori/uuid"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/afero"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "019ae5ada31de202164b118aee88ee2d14075c31"

[[constraint]]
  name = "k8s.io/client-go"
  version = "~5.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "~1.8"

[[override]]
  name = "github.com/russross/blackfriday"
  revision = "93622da34e54fb6529bfb7c57e710f37a8d9cbd8"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/code-generator"

[[override]]
  name = "k8s.io/gengo"
  revision = "9e661e9308f078838e266cca1c673922088c0ea4"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-plugin"
