
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
  creationTimestamp: null
  name: downloadrequests.velero.io
spec:
  group: velero.io
  names:
    kind: DownloadRequest
    listKind: DownloadRequestList
    plural: downloadrequests
    singular: downloadrequest
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: DownloadRequest is a request to download an artifact from backup
          object storage, such as a backup log file.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: DownloadRequestSpec is the specification for a download request.
            properties:
              target:
                description: Target is what to download (e.g. logs for a backup).
                properties:
                  kind:
                    description: Kind is the type of file to download.
                    enum:
                    - BackupLog
                    - BackupContents
                    - BackupVolumeSnapshots
                    - BackupItemOperations
                    - BackupResourceList
                    - BackupResults
                    - RestoreLog
                    - RestoreResults
                    - RestoreResourceList
                    - RestoreItemOperations
                    - CSIBackupVolumeSnapshots
                    - CSIBackupVolumeSnapshotContents
                    type: string
                  name:
                    description: Name is the name of the kubernetes resource with
                      which the file is associated.
                    type: string
                required:
                - kind
                - name
                type: object
            required:
            - target
            type: object
          status:
            description: DownloadRequestStatus is the current status of a DownloadRequest.
            properties:
              downloadURL:
                description: DownloadURL contains the pre-signed URL for the target
                  file.
                type: string
              expiration:
                description: Expiration is when this DownloadRequest expires and can
                  be deleted by the system.
                format: date-time
                nullable: true
                type: string
              phase:
                description: Phase is the current state of the DownloadRequest.
                enum:
                - New
                - Processed
                type: string
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
