---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.5
  name: datadownloads.velero.io
spec:
  group: velero.io
  names:
    kind: DataDownload
    listKind: DataDownloadList
    plural: datadownloads
    singular: datadownload
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: DataDownload status such as New/InProgress
      jsonPath: .status.phase
      name: Status
      type: string
    - description: Time duration since this DataDownload was started
      jsonPath: .status.startTimestamp
      name: Started
      type: date
    - description: Completed bytes
      format: int64
      jsonPath: .status.progress.bytesDone
      name: Bytes Done
      type: integer
    - description: Total bytes
      format: int64
      jsonPath: .status.progress.totalBytes
      name: Total Bytes
      type: integer
    - description: Name of the Backup Storage Location where the backup data is stored
      jsonPath: .spec.backupStorageLocation
      name: Storage Location
      type: string
    - description: Time duration since this DataDownload was created
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: Name of the node where the DataDownload is processed
      jsonPath: .status.node
      name: Node
      type: string
    name: v2alpha1
    schema:
      openAPIV3Schema:
        description: DataDownload acts as the protocol between data mover plugins
          and data mover controller for the datamover restore operation
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: DataDownloadSpec is the specification for a DataDownload.
            properties:
              backupStorageLocation:
                description: |-
                  BackupStorageLocation is the name of the backup storage location
                  where the backup repository is stored.
                type: string
              cancel:
                description: |-
                  Cancel indicates request to cancel the ongoing DataDownload. It can be set
                  when the DataDownload is in InProgress phase
                type: boolean
              dataMoverConfig:
                additionalProperties:
                  type: string
                description: DataMoverConfig is for data-mover-specific configuration
                  fields.
                type: object
              datamover:
                description: |-
                  DataMover specifies the data mover to be used by the backup.
                  If DataMover is "" or "velero", the built-in data mover will be used.
                type: string
              nodeOS:
                description: NodeOS is OS of the node where the DataDownload is processed.
                enum:
                - auto
                - linux
                - windows
                type: string
              operationTimeout:
                description: |-
                  OperationTimeout specifies the time used to wait internal operations,
                  before returning error as timeout.
                type: string
              snapshotID:
                description: SnapshotID is the ID of the Velero backup snapshot to
                  be restored from.
                type: string
              sourceNamespace:
                description: |-
                  SourceNamespace is the original namespace where the volume is backed up from.
                  It may be different from SourcePVC's namespace if namespace is remapped during restore.
                type: string
              targetVolume:
                description: TargetVolume is the information of the target PVC and
                  PV.
                properties:
                  namespace:
                    description: Namespace is the target namespace
                    type: string
                  pv:
                    description: PV is the name of the target PV that is created by
                      Velero restore
                    type: string
                  pvc:
                    description: PVC is the name of the target PVC that is created
                      by Velero restore
                    type: string
                required:
                - namespace
                - pv
                - pvc
                type: object
            required:
            - backupStorageLocation
            - operationTimeout
            - snapshotID
            - sourceNamespace
            - targetVolume
            type: object
          status:
            description: DataDownloadStatus is the current status of a DataDownload.
            properties:
              acceptedByNode:
                description: Node is name of the node where the DataUpload is prepared.
                type: string
              acceptedTimestamp:
                description: |-
                  AcceptedTimestamp records the time the DataUpload is to be prepared.
                  The server's time is used for AcceptedTimestamp
                format: date-time
                nullable: true
                type: string
              completionTimestamp:
                description: |-
                  CompletionTimestamp records the time a restore was completed.
                  Completion time is recorded even on failed restores.
                  The server's time is used for CompletionTimestamps
                format: date-time
                nullable: true
                type: string
              message:
                description: Message is a message about the DataDownload's status.
                type: string
              node:
                description: Node is name of the node where the DataDownload is processed.
                type: string
              phase:
                description: Phase is the current state of the DataDownload.
                enum:
                - New
                - Accepted
                - Prepared
                - InProgress
                - Canceling
                - Canceled
                - Completed
                - Failed
                type: string
              progress:
                description: |-
                  Progress holds the total number of bytes of the snapshot and the current
                  number of restored bytes. This can be used to display progress information
                  about the restore operation.
                properties:
                  bytesDone:
                    format: int64
                    type: integer
                  totalBytes:
                    format: int64
                    type: integer
                type: object
              startTimestamp:
                description: |-
                  StartTimestamp records the time a restore was started.
                  The server's time is used for StartTimestamps
                format: date-time
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
