#baseURL: "https://velero.io/"
disablePathToLower: true
languageCode: en-us
DefaultContentLanguage: "en"
title: Velero
frontmatter:
  date: [":filename", ":default"]
params:
  author: Velero Authors
  vm_logo: vm-logo.png
  logo: Velero.svg
  hero:
    backgroundColor: med-blue
  versioning: true
  latest: v1.4
  versions:
    - main
    - v1.4
    - v1.3.2
    - v1.3.1
    - v1.3.0
    - v1.2.0
    - v1.1.0
    - v1.0.0
    - v0.11.0
    - v0.10.0
    - v0.9.0
    - v0.8.1
    - v0.8.0
    - v0.7.1
    - v0.7.0
    - v0.6.0
    - v0.5.0
    - v0.4.0
    - v0.3.0
  gh_repo: https://github.com/vmware-tanzu/velero
  footer:
    title: Getting Started
    content: To help you get started, see the documentation.
    cta_title: ''
    cta_url: /docs
    cta_text: Documentation
    vm_link: http://vmware.github.io/
  footer_social_links:
    - title: Twitter
      fa_icon: fab fa-twitter
      url: https://twitter.com/projectvelero
    - title: Slack
      fa_icon: fab fa-slack
      url: https://kubernetes.slack.com/messages/velero
    - title: Google Groups
      fa_icon: fas fa-users
      url: https://groups.google.com/forum/#!forum/projectvelero
    - title: RSS
      fa_icon: fa fa-rss
      url: blog/index.xml
    - title: GitHub
      fa_icon: fab fa-github
      url: https://github.com/vmware-tanzu/velero
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: true
  minifyOutput: false
  tdewolff:
    css:
      decimals: -1
      keepCSS2: true
    html:
      keepConditionalComments: true
      keepDefaultAttrVals: true
      keepDocumentTags: true
      keepEndTags: true
      keepQuotes: true
      keepWhitespace: false
    js: {}
    json: {}
    svg:
      decimals: -1
    xml:
      keepWhitespace: false
enableRobotsTXT: true
enableGitInfo: true
permalinks:
  posts: "/blog/:slug/"
outputs:
  home: ["HTML"]
  section: ["HTML"]
  page: ["HTML"]
  taxonomy: ["HTML"]
  term: ["HTML"]