
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: velero-perms
rules:
- apiGroups:
  - velero.io
  resources:
  - backups
  verbs:
  - create
- apiGroups:
  - velero.io
  resources:
  - backupstoragelocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velero.io
  resources:
  - backupstoragelocations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - velero.io
  resources:
  - downloadrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velero.io
  resources:
  - downloadrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - velero.io
  resources:
  - schedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velero.io
  resources:
  - schedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - velero.io
  resources:
  - serverstatusrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velero.io
  resources:
  - serverstatusrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - velero.io
  resources:
  - podvolumebackup
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velero.io
  resources:
  - podvolumebackup/status
  verbs:
  - get
  - patch
  - update