name: Pull Request Changelog Check
on: [pull_request]
jobs:

  build:
    name: Run Changelog Check
    runs-on: ubuntu-latest
    steps:

    - name: Check out the code
      uses: actions/checkout@v2

    - name: Changelog check
      if: ${{ !(contains(github.event.pull_request.labels.*.name, 'changelog-not-required') || contains(github.event.pull_request.labels.*.name, 'Design') || contains(github.event.pull_request.labels.*.name, 'Website') || contains(github.event.pull_request.labels.*.name, 'Documentation'))}}
      run: ./hack/changelog-check.sh
