name: Pull Request Codespell Check
on: [pull_request]
jobs:

  codespell:
    name: Run Codespell
    runs-on: ubuntu-latest
    steps:

    - name: Check out the code
      uses: actions/checkout@v2

    - name: Codespell
      uses: codespell-project/actions-codespell@master
      with:
        # ignore the config/.../crd.go file as it's generated binary data that is edited elswhere.
        skip: .git,*.png,*.jpg,*.woff,*.ttf,*.gif,*.ico,./config/crd/v1beta1/crds/crds.go,./config/crd/v1/crds/crds.go,,./config/crd/v1alpha1/crds/crds.go,./go.sum,./LICENSE
        ignore_words_list: iam,aks,ist,bridget,ue,shouldnot,atleast
        check_filenames: true
        check_hidden: true
